# ------------------------------------------------------------------
# Configuración de Recursos Compartidos - Este archivo define cómo se comparten los datos con Windows.
# ------------------------------------------------------------------

[Facturacion_Climair]
   comment = Carpeta de Contabilidad y Facturas
   path = /srv/climair/facturacion
   browseable = yes
   read only = no
   guest ok = no
   valid users = @administracion
   create mask = 0770
   directory mask = 0770

[Partes_Climair]
   comment = Registro de instalaciones y mantenimiento
   path = /srv/climair/partes_trabajo
   browseable = yes
   read only = no
   guest ok = no
   valid users = @administracion, @tecnicos
   create mask = 0770
   directory mask = 0770